name: 'action-docker-publish'
description: Build a Docker image and push to a container registry
inputs:
  registry:
    description: Container registry to publish image to
    required: false
    default: 'docker.io'
  password: 
    description: Container registry password
    required: true
  username:
    description: Container registry username.
    require: true
  image_name:
    description: Name of the image.
    require: true
  build_context:
    description: The path to the build context
    require: false
    default: './'
  dockerfile_path:
    description: The full path (including the filename) to the dockerfile that you want to build
    require: false
    default: './Dockerfile'
  cache:
    description: Attempt to use last image as the cache
    require: false
    default: false
  static_tags:
    description: A space-delimited list of static tags for the image
    require: false
  tag_ref:
    description: Tag image with branch or tag name
    require: false
    default: true
  tag_latest:
    description: Tag image as latest
    require: false
    default: false
  tag_version:
    description: Tag image using the version label from Dockerfile (if present)
    require: false
    default: false
  tag_sha:
    description: Tag image using the git commit sha
    require: false
    default: false
  tag_timestamp: 
    description: Tag image with timestamp as %Y-%m-%d_%H%M%S%N
    require: false
    default: false
branding:
  color: 'purple'
  icon: 'layers'
runs:
  using: 'docker'
  image: 'Dockerfile'
